#!/usr/bin/env bash

# Install the regular package first to get the systemd unit file setup.
# Just know that you will have to redo your redis_compile as
# an additional step during upgrades! Otherwise you will return 
# to the packaged version. Comment this out if you want to handle that differently!
# One option is to set the immutable bit on /usr/bin/redis-server, see the 
# commented section at the very end. Using the immutable bit here could
# cause automated patching to fail.

dirnm=$(echo $1 | rev | cut -d'.' -f3- | rev)

aptitude install redis -y 
systemctl stop redis

# Args will pass the tarball name so we can change easily.
# I am using redis-6.0.10.tar.gz at this time.

rm -rf $1
wget https://download.redis.io/releases/"$1"
rm -rf $dirnm
tar xzvf "$1" || exit 1
cd $dirnm || exit 1
apt-get install make gcc -y
apt-get install libssl-dev -y
apt-get install tcl8.6 -y
apt-get install pkg-config -y
apt-get install tcl-tls -y
apt-get install libhiredis-dev -y
make MALLOC=libc BUILD_TLS=yes USE_SYSTEMD=yes
make test
./utils/gen-test-certs.sh
./runtest --tls
cp src/redis-server /usr/bin/redisrolling
# Commented out as to not conflict per deb build req: ln -sf /usr/bin/redisrolling /usr/bin/redis-server
# but you might do A/B by switching the symlink like that.

systemctl restart redis

cd .. && rm -rf $dirnm $1

# Un-comment to set the immutable bit:
# chattr +i /usr/bin/redis-server
